apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: videotypes-demo-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: videotypes
  minReplicas: 1
  maxReplicas: 5
  metrics: 
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 95