apiVersion: apps/v1
kind: Deployment
metadata:
  name: yt
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: yt
  template:
    metadata:
      labels:
        app: yt
    spec:
      serviceAccountName: experiments
      containers:
        - name: voila
          image: eu.gcr.io/projectX-data-science/yt:latest
          command:
            - /bin/bash
            - "-c"
            - |
              poetry run voila "main.ipynb" \
                --port 8888 \
                --Voila.tornado_settings="allow_origin=*" \
                --debug \
                --no-browser \
                --Voila.ip='0.0.0.0' \
                --base_url="${NB_PREFIX}/" \
                --MappingKernelManager.cull_interval=60 \
                --MappingKernelManager.cull_idle_timeout=3600
          resources:
            requests:
              memory: "500Mi"
              cpu: "1000m"
            limits:
              memory: "2000Mi"
              cpu: "1100m"
          ports:
            - containerPort: 8888
          imagePullPolicy: Always