apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: demos-bc
spec:
  healthCheck:
    requestPath: /voila/static/require.min.js
    type: HTTP
  iap:
    enabled: true
    oauthclientCredentials:
      secretName: oauth-client-secret
