apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ingress.yaml
- tls-certificates.yaml
- iap-config.yaml
# Demos:
- showcase-demo-for-researchers
- sensitive-topic-tagger
- showcase-api-demo
- videotypes
- playlist-recommendation-demo
- yt
- questionable-demo
- semantic-demo
